import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import SessionWrapper from "../components/SessionWrapper";
import Foot from "../components/footter";
import Sidebar, { SidebarItem } from '../app/sidebar'
import { Radio,Folder ,Settings, LayoutDashboard  } from "lucide-react";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body className="antialiased">
          <div className="flex flex-col h-screen">
            <Navbar />

            <div className="flex flex-1 overflow-hidden">
              <Sidebar>
                <SidebarItem icon={<LayoutDashboard />}  href="/Dashboard" text="Dashboard" />
                <SidebarItem icon={<Radio />} href="/robot" text="MT5 Signal Bot" />
                <hr className="my-3" />
                <SidebarItem icon={<Settings />} href="/settings"text="Settings" />
              </Sidebar>

              <div className="flex-1 overflow-y-auto">
                {children}
              </div>
              
            </div>
          </div>
        </body>
      </html>
    </SessionWrapper>
  );
}
