
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import SessionWrapper from "../components/SessionWrapper";
import Foot from "../components/footter";
import Sidebar, { SidebarItem } from '../app/sidebar'
import { Radio,History ,Settings, LayoutDashboard,SlidersHorizontal ,ReceiptText, Shield, Users } from "lucide-react";
import { getServerSession } from "next-auth";
import { authOptions } from "../../lib/authOptions";
import { useSession } from "next-auth/react";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) 
{
  const session = await getServerSession(authOptions);
  return (
    <SessionWrapper>
      <html lang="en">
        <body className="antialiased">
          <div className="flex flex-col h-screen">
            <Navbar />

            <div className="flex flex-1 overflow-hidden">
              <Sidebar>
                <SidebarItem icon={<LayoutDashboard />}  href="/Dashboard" text="Dashboard" session={session} />
                <SidebarItem icon={<Radio />} href="/robot" text="MT5 Signal Bot" session={session} /> 
                <SidebarItem icon={<SlidersHorizontal />} href="/control_panel" text="Control Panel" session={session}/>
                {/* <SidebarItem icon={<History />} href="/trade_history" text="Trade History" /> */}
                <SidebarItem icon={<ReceiptText/>} href="/Bills" text="Bills" session={session} />
                <SidebarItem icon={<Shield />} href="/admin_manager" text="Admin"  session={session} forRole="admin"/>
                <hr className="my-3" />
                <SidebarItem icon={<Settings />} href="/settings"text="Settings"  session={session}/>
              </Sidebar>

              <div className="flex-1 overflow-y-auto">
                {children}
              </div>
              
            </div>
          </div>
        </body>
      </html>
    </SessionWrapper>
  );
}
