
import { LayoutDashboard, Radio, ReceiptText, Settings, Shield, SlidersHorizontal } from "lucide-react";
import type { Metadata } from "next";
import Sidebar, { SidebarItem } from '../app/sidebar';
import SessionWrapper from "../components/SessionWrapper";
import "./globals.css";
import Navbar from "./Navbar";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) 
{
  return (
    <SessionWrapper>
      <html lang="en">
        <body className="antialiased">
          <div className="flex flex-col h-screen">
            <Navbar />

            <div className="flex flex-1 overflow-hidden">
              <Sidebar>
                <SidebarItem icon={<LayoutDashboard />}  href="/Dashboard" text="Dashboard"  />
                <SidebarItem icon={<Radio />} href="/robot" text="MT5 Signal Bot" /> 
                <SidebarItem icon={<SlidersHorizontal />} href="/control_panel" text="Control Panel" />
                {/* <SidebarItem icon={<History />} href="/trade_history" text="Trade History" /> */}
                <SidebarItem icon={<ReceiptText/>} href="/Bills" text="Bills" />
                <SidebarItem icon={<Shield />} href="/admin_manager" text="Admin"  forRole="admin"/>
                <hr className="my-3" />
                <SidebarItem icon={<Settings />} href="/profile"text="Settings"  />
              </Sidebar>

              <div className="flex-1 overflow-y-auto">
                {children}
              </div>
              
            </div>
          </div>
        </body>
      </html>
    </SessionWrapper>
  );
}
